import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
const [repo,out]=process.argv.slice(2);
const mod=p=>import(pathToFileURL(path.join(repo,p)));
const {mintReleaseIdentity}=await mod('packages/identity/src/release-identity.mjs');
const {fingerprintTruthRevision}=await mod('contracts/core/v2.0.0/tools/common.mjs');
const {projectCoreReleaseDecision,nativeIdentifierConformsToCore}=await mod('packages/identity/src/core-conformance.mjs');
const require=createRequire(path.join(repo,'package.json'));
const Ajv=require('ajv/dist/2020.js');
const ajv=new Ajv({strict:false,allErrors:true});
ajv.addFormat('date-time', value=>typeof value==='string'&&Number.isFinite(Date.parse(value)));
ajv.addFormat('date', value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value)));
ajv.addFormat('uri', value=>{try{new URL(value);return true;}catch{return false;}});
for(const file of ['common.schema.json','release.schema.json'])ajv.addSchema(JSON.parse(await fs.readFile(path.join(repo,'contracts/core/v2.0.0/schemas',file),'utf8')));
const validate=ajv.getSchema('https://ushso.org/contracts/core/v2.0.0/schemas/release.schema.json');
const validateNative=ajv.compile({$ref:'https://ushso.org/contracts/core/v2.0.0/schemas/common.schema.json#/$defs/nativeIdentifier'});
const fixture=await fs.readFile(path.join(repo,'contracts/core/v2.0.0/bundle/valid-bundle.json'));
const release=JSON.parse(fixture).releases[0], native=release.native_identifiers[0];
const input={asset_id:release.asset_id,source_id:native.source_id,publisher_identifiers:[native],locator:{kind:'exact_distribution',url:'https://example.org/release.csv',evidence_ids:native.evidence_ids},publisher_version:release.publisher_version,release_kind:release.release_kind,evidence_ids:native.evidence_ids,observed_at:'2026-09-03T22:22:33.908Z'};
const identity=mintReleaseIdentity(input);
const envelope={...structuredClone(release),release_id:identity.release_id,entity_id:identity.release_id};
envelope.canonical_content_fingerprint=fingerprintTruthRevision(envelope);
const withFingerprint=patch=>{const e={...envelope,...patch};e.canonical_content_fingerprint=fingerprintTruthRevision(e);return e;};
const cases=[];
const check=(id,fn)=>{try{const r=fn();cases.push({id,...r,status:r.pass?'passed':'failed'});}catch(e){cases.push({id,status:'probe_error',error:e.stack});}};
const rejected=fn=>{try{const r=fn();return {pass:r.projected===false,actual:r};}catch(e){return {pass:true,actual:{error:e.message}};}};
check('control-valid-core-envelope',()=>{const r=projectCoreReleaseDecision(identity,{envelope});return {pass:validate(envelope)&&r.projected===true&&validate(r.core_object)&&r.core_object.canonical_content_fingerprint===fingerprintTruthRevision(r.core_object),actual:{envelope_valid:validate(envelope),projected:r.projected,projected_core_valid:validate(r.core_object),errors:validate.errors}};});
check('foreign-core-asset',()=>rejected(()=>projectCoreReleaseDecision(identity,{envelope:withFingerprint({asset_id:'urn:ushso:asset:foreign'})})));
check('foreign-core-entity-id',()=>rejected(()=>projectCoreReleaseDecision(identity,{envelope:withFingerprint({entity_id:'urn:ushso:release:foreign'})})));
check('incomplete-core-envelope',()=>rejected(()=>projectCoreReleaseDecision(identity,{envelope:{contract_version:'observatory-core.v2.0.0',entity_type:'Release',asset_id:identity.asset_id,release_id:identity.release_id}})));
check('invalid-native-effective-date',()=>{const invalid={...native,effective_from:'invalid-date'};return {pass:!nativeIdentifierConformsToCore(invalid),actual:{frozen_schema_accepts:validateNative(invalid),adapter_accepts:nativeIdentifierConformsToCore(invalid),schema_errors:validateNative.errors}};});
check('unicode-identifier-collision',()=>{const valueA=String.fromCodePoint(0x1f600),valueB=String.fromCodePoint(0x1f60)+'0';const mint=value=>mintReleaseIdentity({...input,publisher_identifiers:[{...native,value,normalized_value:value}]});const a=mint(valueA),b=mint(valueB);return {pass:a.release_id!==b.release_id,actual:{value_a:valueA,value_b:valueB,release_a:a.release_id,release_b:b.release_id,state_a:a.identity_state,state_b:b.identity_state}};});
const hash=b=>createHash('sha256').update(b).digest('hex');
await fs.mkdir(out,{recursive:true});
const report={format:'ushso.pr007-controller-r2-additional-semantics.v1',recorded_at:new Date().toISOString(),synthetic_inputs:true,core_fixture_sha256:hash(fixture),source_fixture_unchanged:hash(fixture)===hash(await fs.readFile(path.join(repo,'contracts/core/v2.0.0/bundle/valid-bundle.json'))),script_sha256:hash(await fs.readFile(new URL(import.meta.url))),cases,accepted:false};
await fs.writeFile(path.join(out,'semantics.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({cases:cases.map(x=>({id:x.id,status:x.status})),report:path.join(out,'semantics.json')}));process.exitCode=cases.every(x=>x.status==='passed')?0:1;
