import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {parseGrid} from '../scripts/research/cms-grid-parser.mjs';
const span=(text,x,y)=>({text,x,y});
function page(number=1){return {page:number,status:'captured',rectangles:[[0,0,1,100],[100,0,101,100],[200,0,201,100],[400,0,401,100],...[90,80,50,20].map(y=>[0,y,401,y+1])],spans:[span('Variable Name',10,85),span('Term Name',110,85),span('Definition',210,85),span('current',10,65),span('Current',110,65),span('Current definition first.',210,75),span('Current definition last.',210,55),span('prior',10,35),span('Prior',110,35),span('Prior definition first.',210,45),span('Prior definition last.',210,25)]};}
const document=pages=>({mode:'painted-bordered-grid-v2',total_pages:pages.length,pages});
test('centered variable owns only text inside its publisher row',()=>{const r=parseGrid(document([page()]));assert.equal(r.variables.length,2);assert.equal(r.variables[0].description,'Current definition first. Current definition last.');assert.equal(r.variables[1].description,'Prior definition first. Prior definition last.');assert.equal(r.variables[0].unit,null);assert.equal(r.variables[0].eligible_for_schema_promotion,false);});
test('multipage repeated headers do not become variables',()=>{const second=page(2);second.spans=second.spans.map(s=>({...s,text:s.text==='current'?'later':s.text==='prior'?'last':s.text}));const r=parseGrid(document([page(),second]));assert.equal(r.variables.length,4);assert.deepEqual(r.pages_parsed.map(p=>p.page),[1,2]);});
test('unidentified continuation row stays unresolved, not appended',()=>{const p=page();p.spans=p.spans.filter(s=>s.text!=='prior');const r=parseGrid(document([p]));assert.equal(r.variables.length,1);assert.equal(r.issues[0].code,'GRID_ROW_IDENTITY_OR_CONTINUATION');assert.ok(!r.variables[0].description.includes('Prior'));});
test('duplicate identities across pages are isolated',()=>{const r=parseGrid(document([page(),page(2)]));assert.equal(r.variables.length,0);assert.equal(r.issues.at(-1).code,'GRID_DUPLICATE_VARIABLE_IDENTITY');});
test('missing borders do not fall back to text proximity',()=>{const p=page();p.rectangles=[];const r=parseGrid(document([p]));assert.equal(r.variables.length,0);assert.equal(r.issues[0].code,'GRID_COLUMN_BORDER_MISSING');});
test('malformed peer page does not interrupt a valid page',()=>{const r=parseGrid(document([{page:1,status:'captured',rectangles:{},spans:[]},page(2)]));assert.equal(r.variables.length,2);assert.equal(r.issues[0].code,'GRID_PAGE_UNAVAILABLE');});
test('unsafe geometry and page limit reject explicitly',()=>{const p=page();p.spans[0].x=NaN;assert.equal(parseGrid(document([p])).issues[0].code,'GRID_GEOMETRY');assert.throws(()=>parseGrid(document(Array.from({length:65},()=>page()))),/GRID_DOCUMENT/);});
test('multiline span is isolated instead of assigning two rows to one baseline',()=>{const p=page();p.spans[3].text='current\nprior';const r=parseGrid(document([p]));assert.equal(r.variables.length,0);assert.equal(r.issues[0].code,'GRID_MULTILINE_SPAN_AMBIGUOUS');});
test('legacy unqualified rectangle capture is rejected',()=>{assert.throws(()=>parseGrid({...document([page()]),mode:'bordered-grid-v1'}),/GRID_DOCUMENT/);});
test('actual CMS centered rank definitions retain current/prior ownership',()=>{const r=parseGrid(JSON.parse(fs.readFileSync(new URL('./fixtures/cms-grid-v2/f845155c969ea5e6ad7cd1a83b93efc01565872384da1bfa15fd22de04eb0b1a.json',import.meta.url))));assert.equal(r.variables.length,5);const current=r.variables.find(v=>v.name==='current_fy_rank'),prior=r.variables.find(v=>v.name==='prior_fy_rank');assert.match(current.description,/during the current Fiscal Year/);assert.doesNotMatch(current.description,/during the prior Fiscal Year/);assert.match(prior.description,/during the prior Fiscal Year/);assert.doesNotMatch(prior.description,/during the current Fiscal Year/);});
test('actual CMS two-page ACO dictionary has 36 unique bounded rows',()=>{const r=parseGrid(JSON.parse(fs.readFileSync(new URL('./fixtures/cms-grid-v2/35c43d207e21786f24b2d202beec640d51262ee5accec6f273ca3f9be142755e.json',import.meta.url))));assert.equal(r.variables.length,36);assert.equal(new Set(r.variables.map(v=>v.name)).size,36);assert.deepEqual(r.pages_parsed.map(p=>p.page),[1,2]);assert.equal(r.issues.length,0);assert.ok(r.variables.some(v=>v.page===2));});
