import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRetrievalEngine as control} from './fixtures/direct-base-control.mjs';import {createRetrievalEngine as candidate} from '../packages/retrieval/tools/retrieval-core-v1.2.mjs';
const { corpus, record, vocabulary } = JSON.parse(await fs.readFile(new URL('./fixtures/direct-base-input.json', import.meta.url)));
const cases=[['Hospital costs','hospital cost cost costs','hospital cost'],['Cities and counties','city county counties','city counties'],['Boxes churches dishes','box church dish','boxes churches'],['Café naïve HÔSPITAL','résumé children mortality','cafe hospital'],['hospital-costs, county/rates','hospital; cost: rates','hospital costs'],['hospital','cost reports','hospital cost reports'],['hospitals hospitals hospital','costs costs cost cost','hospital costs'],['buses bus business','businesses analyses analysis','bus business']];
function withoutFacetLabels(value) {
 const copy=structuredClone(value);
 for(const section of copy.facets?.sections ?? []) for(const option of section.options) option.label='[facet-label]';
 return copy;
}
for(const [title,description,question] of cases)test('byte parity and immutable input: '+title,()=>{const rows=[structuredClone(record)];rows[0].title=title;rows[0].description=description;const before=JSON.stringify(rows),args={records:rows,searchDocuments:null,vocabulary,corpus,catalogValidation:{valid:rows,invalid:[]}};const a=control(args),b=candidate(args);for(const sort of ['canonical_relevance','title_asc','release_newest','observation_latest']){const query={question,sort,limit:10};assert.deepEqual(withoutFacetLabels(b.retrieve(query)),withoutFacetLabels(a.retrieve(query)));}assert.equal(JSON.stringify(rows),before);});
test('raw-token dedup preserves singular-token order including duplicates and boundaries',()=>{const singular=token=>token.length>4&&token.endsWith('ies')?token.slice(0,-3)+'y':token.length>4&&/(?:ches|shes|xes|zes|oes)$/.test(token)?token.slice(0,-2):token.length>3&&token.endsWith('s')&&!token.endsWith('ss')?token.slice(0,-1):token;for(const text of ['cities city cities counties county','boxes box churches church dishes dish','bus buses business businesses','hospital hospital costs cost','a b a c b']){const old=[...new Set(text.split(' ').filter(Boolean).map(singular))].join(' '),next=[...new Set([...new Set(text.split(' ').filter(Boolean))].map(singular))].join(' ');assert.equal(next,old);}});
