import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {ensureResearchArchive} from '../scripts/prepare-research-assets.mjs';
const tempBase=process.env.TMPDIR??process.env.RUNNER_TEMP;
assert.ok(tempBase&&path.isAbsolute(tempBase),'tests require TMPDIR or RUNNER_TEMP');
const payload=Buffer.from('retained archive fixture');
const archive={bytes:payload.length,sha256:createHash('sha256').update(payload).digest('hex'),url:'https://github.com/ajhcs/ushso/releases/download/research-assets-test/research-assets-test.tar.gz'};
async function fixture(fn){const directory=await fs.mkdtemp(path.join(tempBase,'ushso-fetch-test-'));try{await fn(path.join(directory,'archive.tar.gz'),directory);}finally{await fs.rm(directory,{recursive:true,force:true});}}
test('valid retained archive needs no network',()=>fixture(async file=>{await fs.writeFile(file,payload);await ensureResearchArchive({archive,file,fetchImpl:()=>assert.fail('unexpected network')});}));
test('existing incorrect bytes fail without overwrite or download',()=>fixture(async file=>{const wrong=Buffer.alloc(payload.length,88);await fs.writeFile(file,wrong);await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:()=>assert.fail('unexpected network')}),/RESEARCH_SOURCE_HASH/);assert.deepEqual(await fs.readFile(file),wrong);}));
test('valid missing archive is installed only after digest verification',()=>fixture(async(file,directory)=>{await ensureResearchArchive({archive,file,fetchImpl:async()=>new Response(payload)});assert.deepEqual(await fs.readFile(file),payload);assert.deepEqual(await fs.readdir(directory),['archive.tar.gz']);}));
test('download digest failure removes temporary bytes',()=>fixture(async(file,directory)=>{await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:async()=>new Response(Buffer.alloc(payload.length,88))}),/RESEARCH_SOURCE_HASH/);assert.deepEqual(await fs.readdir(directory),[]);}));
test('chunked download cannot exceed pinned byte count',()=>fixture(async(file,directory)=>{await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:async()=>new Response(Buffer.concat([payload,Buffer.from('extra')]))}),/RESEARCH_SOURCE_SIZE/);assert.deepEqual(await fs.readdir(directory),[]);}));
test('unexpected source URL is rejected before fetching',()=>fixture(async file=>{await assert.rejects(ensureResearchArchive({archive:{...archive,url:'https://example.com/archive.tar.gz'},file,fetchImpl:()=>assert.fail('unexpected network')}),/RESEARCH_SOURCE_URL/);}));
test('competing cache bytes are never overwritten',()=>fixture(async(file,directory)=>{const competing=Buffer.alloc(payload.length,88);await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:async()=>{await fs.writeFile(file,competing);return new Response(payload);}}),/RESEARCH_SOURCE_HASH/);assert.deepEqual(await fs.readFile(file),competing);assert.deepEqual(await fs.readdir(directory),['archive.tar.gz']);}));
test('cache symlink is rejected without modifying target',()=>fixture(async(file,directory)=>{const target=path.join(directory,'target');await fs.writeFile(target,payload);await fs.symlink(target,file);await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:()=>assert.fail('unexpected network')}),/RESEARCH_SOURCE_SIZE_OR_TYPE/);assert.deepEqual(await fs.readFile(target),payload);}));
test('unexpected HTTP and length do not create cache files',()=>fixture(async(file,directory)=>{await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:async()=>new Response('missing',{status:404})}),/RESEARCH_SOURCE_HTTP/);await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:async()=>new Response(payload,{headers:{'content-length':'1'}})}),/RESEARCH_SOURCE_LENGTH/);assert.deepEqual(await fs.readdir(directory),[]);}));
test('GitHub release redirects are bounded to HTTPS GitHub asset hosts',()=>fixture(async(file,directory)=>{const calls=[];await ensureResearchArchive({archive,file,fetchImpl:async(url)=>{calls.push(url);if(calls.length===1)return new Response(null,{status:302,headers:{location:'https://release-assets.githubusercontent.com/github-production-release-asset/example'}});return new Response(payload);}});assert.deepEqual(calls,[archive.url,'https://release-assets.githubusercontent.com/github-production-release-asset/example']);assert.deepEqual(await fs.readFile(file),payload);}));
test('external release redirects are rejected before a second request',()=>fixture(async(file)=>{let calls=0;await assert.rejects(ensureResearchArchive({archive,file,fetchImpl:async()=>{calls+=1;return new Response(null,{status:302,headers:{location:'https://example.com/archive.tar.gz'}});}}),/RESEARCH_SOURCE_REDIRECT/);assert.equal(calls,1);}));
test('symlinked cache parents cannot redirect the archive write',()=>fixture(async(file,directory)=>{const real=path.join(directory,'real');const linked=path.join(directory,'linked');await fs.mkdir(real);await fs.symlink(real,linked);const linkedFile=path.join(linked,'archive.tar.gz');await assert.rejects(ensureResearchArchive({archive,file:linkedFile,fetchImpl:()=>assert.fail('unexpected network')}),/RESEARCH_SOURCE_CACHE_PATH/);assert.deepEqual(await fs.readdir(real),[]);}));
test('archive bounds match the staging extractor ceiling',()=>fixture(async(file)=>{await assert.rejects(ensureResearchArchive({archive:{...archive,bytes:8*1024**3+1},file,fetchImpl:()=>assert.fail('unexpected network')}),/RESEARCH_SOURCE_LOCK/);}));

test('existing descendants cannot hide a symlinked cache ancestor',()=>fixture(async(file,directory)=>{const real=path.join(directory,'real'),linked=path.join(directory,'linked');await fs.mkdir(path.join(real,'existing'),{recursive:true});await fs.symlink(real,linked);await assert.rejects(ensureResearchArchive({archive,file:path.join(linked,'existing','new','archive.tar.gz'),fetchImpl:()=>assert.fail('unexpected network')}),/RESEARCH_SOURCE_CACHE_PATH/);assert.deepEqual(await fs.readdir(path.join(real,'existing')),[]);}));
