import { useEffect, useRef, useState } from 'react'
import ScientificConflictsPanel from './ScientificConflictsPanel'
type Passage = { url: string; source_sha256: string; page: number; literal: string }
type Row = { claim: { claim_id: string; card_id: string; proposal_sha256: string; proposed_value: { text: string; year_basis?: string }; owner_decision: null }; passages: Passage[] }
type Review = { record_id: string; generation: string; manifest_sha256: string; owner_decision: null; publication_authorized: false; canonical_records_changed: 0; claims: Row[] }
export default function ScientificReviewPanel({ recordId, generation }: { recordId: string; generation: string }) {
 const [review,setReview]=useState<Review|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(false)
 const active=useRef<AbortController|null>(null)
 useEffect(()=>()=>active.current?.abort(),[recordId,generation])
 async function load(){active.current?.abort();const controller=new AbortController();active.current=controller;setLoading(true);setError(null);setReview(null)
  try{const response=await fetch(`/api/research/v1/scientific-review?${new URLSearchParams({record_id:recordId,generation})}`,{signal:controller.signal,headers:{accept:'application/json'}});if(!response.body)throw Error('review_unavailable');const reader=response.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>64*1024)throw Error('review_response_limit');chunks.push(value)}}finally{await reader.cancel();reader.releaseLock()}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}const body=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));if(!response.ok)throw Error(body.error?.code??'review_unavailable');const r=body.result
   if(body.schema!=='ushso.scientific-review-response.v1'||r?.record_id!==recordId||r.generation!==generation||r.owner_decision!==null||r.publication_authorized!==false||r.canonical_records_changed!==0||!Array.isArray(r.claims)||r.claims.length>4)throw Error('review_identity_or_boundary')
   if(!r.claims.every((row:Row)=>row?.claim?.owner_decision===null&&typeof row.claim.proposed_value?.text==='string'&&/^[a-f0-9]{64}$/.test(row.claim.proposal_sha256)&&Array.isArray(row.passages)&&row.passages.length<=12&&row.passages.every(p=>{try{const url=new URL(p.url);return url.protocol==='https:'&&url.hostname==='data.cms.gov'&&!url.username&&!url.password&&!url.port&&typeof p.literal==='string'&&p.literal.length<=6000&&/^[a-f0-9]{64}$/.test(p.source_sha256)}catch{return false}})))throw Error('review_claim_shape')
   if(!controller.signal.aborted)setReview(r)
  }catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'review_unavailable')}finally{if(!controller.signal.aborted)setLoading(false)}
 }
 return <><section className="details-panel" style={{overflowWrap:'anywhere'}} aria-labelledby="scientific-review-heading"><h2 id="scientific-review-heading">Scientific claim preview — owner approval pending</h2><p>This separate review overlay does not change the catalog, approve scientific facts, or authorize publication.</p><button type="button" disabled={loading} onClick={()=>void load()}>Inspect pending scientific notes</button>{loading?<p role="status">Loading bounded review evidence…</p>:null}{error?<p role="alert">Review unavailable: {error}. No scientific approval is implied.</p>:null}{review?review.claims.map(row=><article key={row.claim.claim_id}><h3>{row.claim.card_id}: proposed note</h3><p>{row.claim.proposed_value.text}</p>{row.claim.proposed_value.year_basis?<p>Year basis: {row.claim.proposed_value.year_basis}</p>:null}<p>Owner decision: pending. Proposal SHA-256: <code>{row.claim.proposal_sha256}</code></p><details><summary>Public publisher passages and source hashes</summary>{row.passages.map((p,i)=><div key={i}><p><a href={p.url} target="_blank" rel="noreferrer">Publisher document, page {p.page}</a></p><blockquote>{p.literal}</blockquote><p>Source SHA-256: <code>{p.source_sha256}</code></p></div>)}</details></article>):null}{review?<p>Review manifest SHA-256: <code>{review.manifest_sha256}</code></p>:null}</section><ScientificConflictsPanel recordId={recordId} generation={generation}/></>
}
