"""Declared 100-product selection for PR-002 C-002-1.

This is a selection commitment, not a sample-success or payload-access claim.
Annual releases, GIS-friendly redistributions, and duplicate portal records are
not extra products. program_key is intentionally reused when one program
publishes multiple genuine products.
"""

from __future__ import annotations

DOMAINS = (
    "finance",
    "ownership",
    "quality",
    "utilization",
    "workforce",
    "insurance",
    "population",
    "geography",
    "public health",
    "prices",
)

# Each product: see PRODUCT_FIELDS in build.py. resolve.kind is one of:
#   cms_title, cdc_native, census_dataset, intake
# Representative releases bind evidence; they do not create additional products.

PRODUCTS: list[dict] = [
    # --- finance ---
    {
        "product_key": "cms-hcris-hospital-provider-cost-report",
        "program_key": "cms-cost-reports",
        "title": "Hospital Provider Cost Report",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "HCRIS hospital cost-report years and worksheet revisions are releases of this product, not additional products.",
        "rationale": "Named Pennsylvania-finance comparator and the primary national hospital financial statement source.",
        "resolve": {"kind": "cms_title", "title": "Hospital Provider Cost Report"},
    },
    {
        "product_key": "cms-hha-cost-report",
        "program_key": "cms-cost-reports",
        "title": "Home Health Agency Cost Report",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "HHA cost-report years are releases. This is a distinct product from hospital HCRIS inside the same CMS cost-report program.",
        "rationale": "Keeps program_key shared across genuine cost-report products so a program key cannot collapse them.",
        "resolve": {"kind": "cms_title", "title": "Home Health Agency Cost Report"},
    },
    {
        "product_key": "cms-snf-cost-report",
        "program_key": "cms-cost-reports",
        "title": "Skilled Nursing Facility Cost Report",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "SNF cost-report years are releases of this product.",
        "rationale": "Third distinct CMS cost-report product; required for nursing-home finance tasks without treating SNF worksheets as hospital HCRIS.",
        "resolve": {"kind": "cms_title", "title": "Skilled Nursing Facility Cost Report"},
    },
    {
        "product_key": "phc4-hospital-financial-utilization-reports",
        "program_key": "phc4-hospital-reports",
        "title": "PHC4 hospital financial and utilization reports",
        "domain": "finance",
        "publisher": "Pennsylvania Health Care Cost Containment Council",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "PHC4 annual/financial-year publications are releases of this Pennsylvania product family.",
        "rationale": "Named missing family and the HCRIS comparator for Pennsylvania hospital finance; not in the v1.2 catalog.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-044 C-044-1",
            "locator": "https://www.phc4.org/",
            "locator_kind": "publisher_home",
        },
    },
    {
        "product_key": "cms-performance-year-financial-quality-results",
        "program_key": "cms-aco-shared-savings",
        "title": "Performance Year Financial and Quality Results",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "ACO performance years are releases.",
        "rationale": "Population-based payment financial results, distinct from facility cost reports.",
        "resolve": {"kind": "cms_title", "title": "Performance Year Financial and Quality Results"},
    },
    {
        "product_key": "cms-aco-reach-financial-quality-results",
        "program_key": "cms-innovation-center",
        "title": "ACO REACH Financial and Quality Results",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Model performance years are releases of this distinct Innovation Center product.",
        "rationale": "Distinct from Shared Savings performance-year results inside CMS innovation reporting.",
        "resolve": {"kind": "cms_title", "title": "ACO REACH Financial and Quality Results"},
    },
    {
        "product_key": "cms-county-aggregate-expenditure-risk-score",
        "program_key": "cms-geographic-variation",
        "title": "County-level Aggregate Expenditure and Risk Score Data on Assignable Beneficiaries",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual county files are releases.",
        "rationale": "County expenditure/risk scores are a different grain from facility cost reports and from HRR variation tables.",
        "resolve": {"kind": "cms_title", "title": "County-level Aggregate Expenditure and Risk Score Data on Assignable Beneficiaries"},
    },
    {
        "product_key": "cms-medicare-inpatient-hospitals-by-provider",
        "program_key": "cms-medicare-provider-utilization-payment",
        "title": "Medicare Inpatient Hospitals - by Provider",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual PUFs are releases. Provider-and-service files are a different product.",
        "rationale": "Provider-level Medicare payments/charges, not HCRIS worksheets and not the service-line PUF.",
        "resolve": {"kind": "cms_title", "title": "Medicare Inpatient Hospitals - by Provider"},
    },
    {
        "product_key": "aha-annual-survey",
        "program_key": "aha-annual-survey",
        "title": "AHA Annual Survey",
        "domain": "finance",
        "publisher": "American Hospital Association",
        "named_priority": True,
        "access_expectation": "restricted_or_manual_route",
        "product_release_distinction": "Survey years are releases of this restricted/paid product.",
        "rationale": "Named missing family with documented paid/restricted access; catalog membership is absent.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-045 C-045-1",
            "locator": "https://www.ahadata.com/aha-annual-survey-database",
            "locator_kind": "publisher_product_page",
        },
    },
    {
        "product_key": "cms-mcbs-cost-supplement",
        "program_key": "cms-mcbs",
        "title": "Medicare Current Beneficiary Survey - Cost Supplement",
        "domain": "finance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "restricted_or_manual_route",
        "product_release_distinction": "MCBS survey years are releases. The survey file is a distinct product in the same program.",
        "rationale": "Beneficiary-level cost supplement is not a facility cost report and is a harder restricted-route member.",
        "resolve": {"kind": "cms_title", "title": "Medicare Current Beneficiary Survey - Cost Supplement"},
    },
    # --- ownership ---
    {
        "product_key": "cms-hospital-all-owners",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Hospital All Owners",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Enrollment snapshots are releases of this ownership roster product.",
        "rationale": "Source-native hospital owner roster used by ownership tasks; distinct from CHOW event files.",
        "resolve": {"kind": "cms_title", "title": "Hospital All Owners"},
    },
    {
        "product_key": "cms-hospital-change-of-ownership",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Hospital Change of Ownership",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "CHOW event extracts are releases; owner-information files are a distinct product.",
        "rationale": "Event-level hospital CHOW product, not the all-owners roster.",
        "resolve": {"kind": "cms_title", "title": "Hospital Change of Ownership"},
    },
    {
        "product_key": "cms-hospital-change-of-ownership-owner-information",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Hospital Change of Ownership - Owner Information",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Owner-detail extracts accompanying CHOW events; not a second count of the CHOW event product.",
        "rationale": "Owner-grain CHOW details would be collapsed if identity were only (publisher, program).",
        "resolve": {"kind": "cms_title", "title": "Hospital Change of Ownership - Owner Information"},
    },
    {
        "product_key": "cms-hospital-enrollments",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Hospital Enrollments",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Enrollment snapshots are releases.",
        "rationale": "Facility enrollment identity is distinct from owner rosters and CHOW events.",
        "resolve": {"kind": "cms_title", "title": "Hospital Enrollments"},
    },
    {
        "product_key": "cms-snf-all-owners",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Skilled Nursing Facility All Owners",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "SNF owner snapshots are releases of this product, not hospital owner files.",
        "rationale": "Nursing-home ownership is a distinct product in the same enrollment program.",
        "resolve": {"kind": "cms_title", "title": "Skilled Nursing Facility All Owners"},
    },
    {
        "product_key": "cms-snf-change-of-ownership",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Skilled Nursing Facility Change of Ownership",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "SNF CHOW events are releases of this product.",
        "rationale": "Distinct from hospital CHOW; needed so nursing-home ownership tasks do not borrow hospital files.",
        "resolve": {"kind": "cms_title", "title": "Skilled Nursing Facility Change of Ownership"},
    },
    {
        "product_key": "cms-fqhc-all-owners",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Federally Qualified Health Center All Owners",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "FQHC owner snapshots are releases.",
        "rationale": "Outpatient clinic ownership is a distinct enrollment product.",
        "resolve": {"kind": "cms_title", "title": "Federally Qualified Health Center All Owners"},
    },
    {
        "product_key": "cms-hha-all-owners",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Home Health Agency All Owners",
        "domain": "ownership",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "HHA owner snapshots are releases.",
        "rationale": "Post-acute ownership distinct from hospital and SNF owner files.",
        "resolve": {"kind": "cms_title", "title": "Home Health Agency All Owners"},
    },
    {
        "product_key": "census-economic-census-hospital-ownership-control",
        "program_key": "census-economic-census",
        "title": "Economic Census: Health Care and Social Assistance: Ownership and Control of Government Hospitals for the U.S.",
        "domain": "ownership",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Economic Census years (2012/2017/2022) are releases of this product. Representative evidence is ECNHOSP2022.",
        "rationale": "National government-hospital ownership/control tables; 2012 and 2017 copies are not extra products.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ECNHOSP2022"},
    },
    {
        "product_key": "rural-hospital-closure-tracking",
        "program_key": "rural-hospital-closure-tracking",
        "title": "Rural hospital closure tracking",
        "domain": "ownership",
        "publisher": "Cecil G. Sheps Center for Health Services Research, University of North Carolina",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "Dated closure lists are releases. Operator and methodology identity stay with the Sheps Center product.",
        "rationale": "Named missing family. Nongovernmental operator must be preserved; not substitutable by CMS enrollment files.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-044 C-044-1",
            "locator": "https://www.shepscenter.unc.edu/programs-projects/rural-health/rural-hospital-closures/",
            "locator_kind": "publisher_methodology_page",
        },
    },
    # --- quality ---
    {
        "product_key": "cms-ahrq-psi-11-measure-rates",
        "program_key": "cms-hospital-quality-measures",
        "title": "Agency for Healthcare Research and Quality (AHRQ) Patient Safety Indicator 11 (PSI-11) Measure Rates",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Measure years are releases of this PSI-11 product.",
        "rationale": "A specific AHRQ safety indicator, not a generic Hospital Compare dump.",
        "resolve": {"kind": "cms_title", "title": "Agency for Healthcare Research and Quality (AHRQ) Patient Safety Indicator 11 (PSI-11) Measure Rates"},
    },
    {
        "product_key": "cms-quality-payment-program-experience",
        "program_key": "cms-quality-payment-program",
        "title": "Quality Payment Program Experience",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "QPP performance years are releases.",
        "rationale": "Clinician QPP experience is distinct from hospital PSI rates.",
        "resolve": {"kind": "cms_title", "title": "Quality Payment Program Experience"},
    },
    {
        "product_key": "cms-nursing-home-chain-performance-measures",
        "program_key": "cms-nursing-home-quality",
        "title": "Nursing Home Chain Performance Measures",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Quarterly/annual chain-measure files are releases.",
        "rationale": "Chain-level nursing-home quality, not PBJ staffing and not hospital PSI.",
        "resolve": {"kind": "cms_title", "title": "Nursing Home Chain Performance Measures"},
    },
    {
        "product_key": "cms-dra-hospital-acquired-condition-measures",
        "program_key": "cms-hospital-quality-measures",
        "title": "Deficit Reduction Act Hospital-Acquired Condition Measures",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "HAC measure years are releases.",
        "rationale": "Statutory HAC measures are a distinct hospital quality product from PSI-11.",
        "resolve": {"kind": "cms_title", "title": "Deficit Reduction Act Hospital-Acquired Condition Measures"},
    },
    {
        "product_key": "cms-medicare-dialysis-facilities",
        "program_key": "cms-dialysis-quality",
        "title": "Medicare Dialysis Facilities",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Dialysis facility measure years are releases.",
        "rationale": "Facility dialysis quality is outside hospital PSI/HAC products.",
        "resolve": {"kind": "cms_title", "title": "Medicare Dialysis Facilities"},
    },
    {
        "product_key": "cms-provider-of-services-qies",
        "program_key": "cms-provider-of-services",
        "title": "Provider of Services File - Quality Improvement and Evaluation System",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "POS snapshots are releases. IQIES and clinical-lab POS files are distinct products.",
        "rationale": "Certified-provider characteristics used in quality denominators; not a measure file.",
        "resolve": {"kind": "cms_title", "title": "Provider of Services File - Quality Improvement and Evaluation System"},
    },
    {
        "product_key": "cdc-places-local-data-for-better-health",
        "program_key": "cdc-places",
        "title": "PLACES: Local Data for Better Health",
        "domain": "quality",
        "publisher": "Centers for Disease Control and Prevention",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual PLACES releases and county/tract/ZCTA/GIS-friendly files are releases or distribution formats of this one product. Representative evidence is the 2025 county table.",
        "rationale": "Local chronic-disease prevalence used in quality/population context. Counting each annual geography file would inflate the cohort.",
        "resolve": {"kind": "cdc_native", "source_id": "swc5-untb"},
    },
    {
        "product_key": "cms-innovation-center-model-summary",
        "program_key": "cms-innovation-center",
        "title": "Innovation Center Model Summary Information",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Model-inventory snapshots are releases; awardee/participant lists are distinct products.",
        "rationale": "Model-level quality/payment inventory, not ACO REACH results.",
        "resolve": {"kind": "cms_title", "title": "Innovation Center Model Summary Information"},
    },
    {
        "product_key": "cms-esrd-facility-aggregation-group-performance",
        "program_key": "cms-dialysis-quality",
        "title": "End-Stage Renal Disease Facility Aggregation Group Performance",
        "domain": "quality",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "ESRD aggregation-group years are releases, distinct from the facility dialysis file.",
        "rationale": "Group-level ESRD performance would be lost if identity were only program title.",
        "resolve": {"kind": "cms_title", "title": "End-Stage Renal Disease Facility Aggregation Group Performance"},
    },
    {
        "product_key": "cdc-nehrs-qpp-restricted-use",
        "program_key": "cdc-nehrs",
        "title": "2024 National Electronic Health Records Survey (NEHRS) Linked to 2023 Quality Payment Program (QPP) Data, Restricted-use data",
        "domain": "quality",
        "publisher": "National Center for Health Statistics",
        "named_priority": False,
        "access_expectation": "restricted_or_manual_route",
        "product_release_distinction": "Survey/link years are releases of this restricted-use product.",
        "rationale": "Hard restricted catalog member; public-sample targets cannot silently drop it.",
        "resolve": {"kind": "cdc_native", "source_id": "kgm3-tvmi"},
    },
    # --- utilization ---
    {
        "product_key": "cms-medicare-inpatient-hospitals-by-provider-and-service",
        "program_key": "cms-medicare-provider-utilization-payment",
        "title": "Medicare Inpatient Hospitals - by Provider and Service",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual service-line PUFs are releases. This is not the provider-only inpatient PUF.",
        "rationale": "Service-line utilization/payment grain required by advanced hospital-use tasks.",
        "resolve": {"kind": "cms_title", "title": "Medicare Inpatient Hospitals - by Provider and Service"},
    },
    {
        "product_key": "cms-medicare-outpatient-hospitals-by-provider-and-service",
        "program_key": "cms-medicare-provider-utilization-payment",
        "title": "Medicare Outpatient Hospitals - by Provider and Service",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual outpatient service-line PUFs are releases.",
        "rationale": "Outpatient utilization is a distinct product from inpatient PUFs.",
        "resolve": {"kind": "cms_title", "title": "Medicare Outpatient Hospitals - by Provider and Service"},
    },
    {
        "product_key": "cms-hospital-service-area",
        "program_key": "cms-hospital-service-area",
        "title": "Hospital Service Area",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual origin-destination files are releases.",
        "rationale": "Patient-flow service areas, not facility-level PUF rows.",
        "resolve": {"kind": "cms_title", "title": "Hospital Service Area"},
    },
    {
        "product_key": "cms-pac-snf-utilization",
        "program_key": "cms-post-acute-care-utilization",
        "title": "Medicare Post-Acute Care Utilization - Skilled Nursing Facility by Geography and Provider",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "PAC years are releases. Provider-and-service PAC files are a different product.",
        "rationale": "SNF PAC utilization is distinct from SNF cost reports and from hospital PUFs.",
        "resolve": {"kind": "cms_title", "title": "Medicare Post-Acute Care Utilization - Skilled Nursing Facility by Geography and Provider"},
    },
    {
        "product_key": "cms-market-saturation-utilization-state-county",
        "program_key": "cms-market-saturation-utilization",
        "title": "Market Saturation & Utilization State-County",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Quarterly/annual saturation files are releases. CBSA files are a distribution/geography cut, not a second product.",
        "rationale": "County market saturation used in utilization and access analyses.",
        "resolve": {"kind": "cms_title", "title": "Market Saturation & Utilization State-County"},
    },
    {
        "product_key": "cms-medicare-home-health-patients-visits-by-state",
        "program_key": "cms-home-health-utilization",
        "title": "Medicare Home Health Patients and Visits by State",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual state totals are releases.",
        "rationale": "State home-health volume, distinct from HHA cost reports and owner files.",
        "resolve": {"kind": "cms_title", "title": "Medicare Home Health Patients and Visits by State"},
    },
    {
        "product_key": "cms-medicare-covid19-hospitalization-trends",
        "program_key": "cms-medicare-covid19",
        "title": "Medicare COVID-19 Hospitalization Trends",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Dated trend extracts are releases of this COVID hospitalization product.",
        "rationale": "Pandemic hospital-use series that is easy to drop; retained as a difficult time-limited member.",
        "resolve": {"kind": "cms_title", "title": "Medicare COVID-19 Hospitalization Trends"},
    },
    {
        "product_key": "cms-facility-level-mds-frequency",
        "program_key": "cms-minimum-data-set",
        "title": "Facility-Level Minimum Data Set Frequency",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "MDS frequency snapshots are releases. The non-facility MDS Frequency file is a distinct product.",
        "rationale": "Nursing-home assessment volume at facility grain.",
        "resolve": {"kind": "cms_title", "title": "Facility-Level Minimum Data Set Frequency"},
    },
    {
        "product_key": "cms-program-statistics-medicare-inpatient-hospital",
        "program_key": "cms-program-statistics",
        "title": "CMS Program Statistics - Medicare Inpatient Hospital",
        "domain": "utilization",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Program-statistics years are releases. Other CPS tables (Part D, hospice, etc.) are distinct products in the same program.",
        "rationale": "National program-statistics inpatient tables, not the provider PUF.",
        "resolve": {"kind": "cms_title", "title": "CMS Program Statistics - Medicare Inpatient Hospital"},
    },
    {
        "product_key": "ahrq-hcup",
        "program_key": "ahrq-hcup",
        "title": "AHRQ Healthcare Cost and Utilization Project",
        "domain": "utilization",
        "publisher": "Agency for Healthcare Research and Quality",
        "named_priority": True,
        "access_expectation": "restricted_or_manual_route",
        "product_release_distinction": "HCUP databases (NIS, SID, NEDS, and related) are distinct products inside this program; annual files are releases. This freeze records the family pending PR-045 product separation.",
        "rationale": "Named missing family. Restricted/central-distributor products cannot be replaced by CMS inpatient PUFs.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-045 C-045-1",
            "locator": "https://hcup-us.ahrq.gov/",
            "locator_kind": "publisher_program_home",
        },
    },
    # --- workforce ---
    {
        "product_key": "cms-pbj-daily-nurse-staffing",
        "program_key": "cms-payroll-based-journal",
        "title": "Payroll Based Journal Daily Nurse Staffing",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "PBJ quarters are releases. Nurse, non-nurse, and employee-detail files are distinct products in one program.",
        "rationale": "Named nursing-staffing task source.",
        "resolve": {"kind": "cms_title", "title": "Payroll Based Journal Daily Nurse Staffing"},
    },
    {
        "product_key": "cms-pbj-daily-non-nurse-staffing",
        "program_key": "cms-payroll-based-journal",
        "title": "Payroll Based Journal Daily Non-Nurse Staffing",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Non-nurse PBJ quarters are releases of this product, not a second nurse-staffing product.",
        "rationale": "Non-nurse hours are a genuine second PBJ product.",
        "resolve": {"kind": "cms_title", "title": "Payroll Based Journal Daily Non-Nurse Staffing"},
    },
    {
        "product_key": "cms-pbj-employee-detail-nursing-home-staffing",
        "program_key": "cms-payroll-based-journal",
        "title": "Payroll Based Journal Employee Detail Nursing Home Staffing",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Employee-detail quarters are releases of this third PBJ product.",
        "rationale": "Employee-detail grain is not the daily nurse aggregate.",
        "resolve": {"kind": "cms_title", "title": "Payroll Based Journal Employee Detail Nursing Home Staffing"},
    },
    {
        "product_key": "cms-medicare-physicians-other-practitioners-by-provider",
        "program_key": "cms-medicare-provider-utilization-payment",
        "title": "Medicare Physician & Other Practitioners - by Provider",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual physician PUFs are releases. Geography/service cuts are distinct products.",
        "rationale": "Clinician workforce/utilization identity distinct from NPPES.",
        "resolve": {"kind": "cms_title", "title": "Medicare Physician & Other Practitioners - by Provider"},
    },
    {
        "product_key": "cms-public-provider-enrollment",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Medicare Fee-For-Service Public Provider Enrollment",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Enrollment snapshots are releases.",
        "rationale": "Public FFS enrollment file used in workforce identity tasks; not NPPES.",
        "resolve": {"kind": "cms_title", "title": "Medicare Fee-For-Service Public Provider Enrollment"},
    },
    {
        "product_key": "nppes-npi-registry",
        "program_key": "cms-nppes",
        "title": "National Plan and Provider Enumeration System",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "NPPES monthly dumps are releases of this enumeration product. NPI is not CCN.",
        "rationale": "Named missing family. Catalog has no NPPES record; CCN=NPI joins remain forbidden.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-043 C-043-1",
            "locator": "https://download.cms.gov/nppes/NPI_Files.html",
            "locator_kind": "publisher_distribution_page",
        },
    },
    {
        "product_key": "hrsa-area-health-resources-files",
        "program_key": "hrsa-ahrf",
        "title": "HRSA Area Health Resources Files",
        "domain": "workforce",
        "publisher": "Health Resources and Services Administration",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "AHRF release years are releases of this county workforce/resource product.",
        "rationale": "Named missing family for area workforce supply.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-043 C-043-1",
            "locator": "https://data.hrsa.gov/topics/health-workforce/ahrf",
            "locator_kind": "publisher_product_page",
        },
    },
    {
        "product_key": "samhsa-facility-services",
        "program_key": "samhsa-facility-services",
        "title": "SAMHSA facility services data",
        "domain": "workforce",
        "publisher": "Substance Abuse and Mental Health Services Administration",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "Locator/N-SUMHSS vintages are releases. CDC Synar youth-tobacco tables are a different SAMHSA-adjacent catalog product and do not satisfy this family.",
        "rationale": "Named missing family. The catalog Synar tables are not facility-services data.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-043 C-043-1",
            "locator": "https://www.samhsa.gov/data/data-we-collect/n-sumhss-national-substance-use-and-mental-health-services-survey",
            "locator_kind": "publisher_product_page",
        },
    },
    {
        "product_key": "cms-opioid-treatment-program-providers",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Opioid Treatment Program Providers",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "OTP provider snapshots are releases.",
        "rationale": "Behavioral-health facility enrollment, complementary to SAMHSA intake and not a substitute for it.",
        "resolve": {"kind": "cms_title", "title": "Opioid Treatment Program Providers"},
    },
    {
        "product_key": "cms-order-and-referring",
        "program_key": "cms-provider-enrollment-ownership",
        "title": "Order and Referring",
        "domain": "workforce",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Order-and-referring snapshots are releases.",
        "rationale": "Clinician ordering eligibility file used in workforce/identity tasks.",
        "resolve": {"kind": "cms_title", "title": "Order and Referring"},
    },
    # --- insurance ---
    {
        "product_key": "cms-medicare-monthly-enrollment",
        "program_key": "cms-medicare-enrollment",
        "title": "Medicare Monthly Enrollment",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Monthly enrollment extracts are releases of this product.",
        "rationale": "Current Medicare enrollment counts used by insurance-coverage tasks.",
        "resolve": {"kind": "cms_title", "title": "Medicare Monthly Enrollment"},
    },
    {
        "product_key": "cms-medicare-advantage-geographic-variation",
        "program_key": "cms-medicare-advantage",
        "title": "Medicare Advantage Geographic Variation - National & State",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "MA geographic-variation years are releases.",
        "rationale": "MA coverage geography is distinct from Original Medicare enrollment.",
        "resolve": {"kind": "cms_title", "title": "Medicare Advantage Geographic Variation - National & State"},
    },
    {
        "product_key": "cms-health-insurance-exchanges-annual-effectuated-enrollment",
        "program_key": "cms-health-insurance-exchanges",
        "title": "Health Insurance Exchanges Annual Effectuated Enrollment",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Plan years are releases. Monthly effectuated enrollment is a distinct product.",
        "rationale": "Marketplace effectuated enrollment, not QIS issuer identity and not TiC files.",
        "resolve": {"kind": "cms_title", "title": "Health Insurance Exchanges Annual Effectuated Enrollment"},
    },
    {
        "product_key": "cms-medicaid-managed-care",
        "program_key": "cms-medicaid",
        "title": "Medicaid Managed Care",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Medicaid managed-care years are releases. T-MSIS/TAF research files are a different product.",
        "rationale": "Public Medicaid managed-care tables, not TAF restricted research files.",
        "resolve": {"kind": "cms_title", "title": "Medicaid Managed Care"},
    },
    {
        "product_key": "cms-program-statistics-dual-enrollment",
        "program_key": "cms-program-statistics",
        "title": "CMS Program Statistics - Medicare-Medicaid Dual Enrollment",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "CPS years are releases of this dual-enrollment table product.",
        "rationale": "Dual enrollment is a distinct CPS product from inpatient-hospital CPS.",
        "resolve": {"kind": "cms_title", "title": "CMS Program Statistics - Medicare-Medicaid Dual Enrollment"},
    },
    {
        "product_key": "cms-program-statistics-part-d-enrollment",
        "program_key": "cms-program-statistics",
        "title": "CMS Program Statistics - Medicare Part D Enrollment",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "CPS years are releases of this Part D enrollment product.",
        "rationale": "Part D enrollment tables are distinct from Part D spending-by-drug.",
        "resolve": {"kind": "cms_title", "title": "CMS Program Statistics - Medicare Part D Enrollment"},
    },
    {
        "product_key": "cms-monthly-pdp-formulary-pharmacy-network",
        "program_key": "cms-part-d-formulary",
        "title": "Monthly Prescription Drug Plan Formulary and Pharmacy Network Information",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Monthly formulary drops are releases. Quarterly pricing files are a distinct product.",
        "rationale": "Plan formulary/network identity for insurance tasks, not a price MRF.",
        "resolve": {"kind": "cms_title", "title": "Monthly Prescription Drug Plan Formulary and Pharmacy Network Information"},
    },
    {
        "product_key": "cms-tmsis-taf",
        "program_key": "cms-tmsis-taf",
        "title": "CMS T-MSIS Analytic Files",
        "domain": "insurance",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "restricted_or_manual_route",
        "product_release_distinction": "TAF annual research files are releases. Public Medicaid summary tables are not TAF.",
        "rationale": "Named missing family. Restricted TAF must not be confused with public Medicaid Managed Care tables.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-043 C-043-1",
            "locator": "https://www.medicaid.gov/medicaid/data-systems/macbis/medicaid-chip-research-files",
            "locator_kind": "publisher_research-files_page",
        },
    },
    {
        "product_key": "state-apcd-programs",
        "program_key": "state-apcd",
        "title": "State all-payer claims database programs",
        "domain": "insurance",
        "publisher": "State APCD programs (jurisdiction-scoped)",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "Each state APCD is a distinct product inside this family. This freeze records the family; PR-044 selects jurisdictions. One state never implies national completeness.",
        "rationale": "Named missing family. No national APCD payload is asserted.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-044 C-044-1",
            "locator": "https://www.apcdcouncil.org/state-apcd-activities",
            "locator_kind": "secondary_directory_of_state_programs",
        },
    },
    {
        "product_key": "ahrq-meps",
        "program_key": "ahrq-meps",
        "title": "AHRQ Medical Expenditure Panel Survey",
        "domain": "insurance",
        "publisher": "Agency for Healthcare Research and Quality",
        "named_priority": True,
        "access_expectation": "mixed_public_and_restricted",
        "product_release_distinction": "Public-use files and restricted MEPS products are distinct products inside this program; survey years are releases. PR-045 must not label public files restricted solely because a restricted MEPS product exists.",
        "rationale": "Named missing family covering insurance/expenditure microdata.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-045 C-045-1",
            "locator": "https://meps.ahrq.gov/",
            "locator_kind": "publisher_program_home",
        },
    },
    # --- population ---
    {
        "product_key": "census-acs-5year-data-profiles",
        "program_key": "census-acs",
        "title": "ACS 5-Year Data Profiles",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "ACS 5-year vintages are releases. Duplicate portal titles ('American Community Survey: 5-Year Estimates: Data Profiles 5-Year') are not extra products. Representative evidence is ACSDP5Y2024.",
        "rationale": "Core ACS geography/population product for beginner and advanced tasks.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSDP5Y2024"},
    },
    {
        "product_key": "census-acs-1year-data-profiles",
        "program_key": "census-acs",
        "title": "ACS 1-Year Data Profiles",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "ACS 1-year vintages are releases of this product, which is methodologically distinct from the 5-year data profiles. Representative evidence is ACSDP1Y2024.",
        "rationale": "1-year ACS profiles are a genuine second ACS product, not a year of the 5-year files.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSDP1Y2024"},
    },
    {
        "product_key": "census-acs-5year-subject-tables",
        "program_key": "census-acs",
        "title": "ACS 5-Year Subject Tables",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Subject-table vintages are releases. This is not the Data Profiles product.",
        "rationale": "Subject tables carry different table IDs and universes from data profiles.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSST5Y2024"},
    },
    {
        "product_key": "census-acs-5year-detailed-tables",
        "program_key": "census-acs",
        "title": "ACS 5-Year Detailed Tables",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Detailed-table vintages are releases.",
        "rationale": "Detailed tables are the ACS product used for custom geography/variable work.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSDT5Y2024"},
    },
    {
        "product_key": "census-acs-5year-pums",
        "program_key": "census-acs",
        "title": "ACS 5-Year Public Use Microdata Sample",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "PUMS vintages are releases. Puerto Rico PUMS is a distinct product.",
        "rationale": "Microdata product, not an aggregate table series.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSPUMS5Y2024"},
    },
    {
        "product_key": "census-acs-1year-pums",
        "program_key": "census-acs",
        "title": "ACS 1-Year Public Use Microdata Sample",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "1-year PUMS vintages are releases of this product, distinct from 5-year PUMS.",
        "rationale": "1-year microdata is not a year of 5-year PUMS.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSPUMS1Y2024"},
    },
    {
        "product_key": "cms-mcbs-survey-file",
        "program_key": "cms-mcbs",
        "title": "Medicare Current Beneficiary Survey - Survey File",
        "domain": "population",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "restricted_or_manual_route",
        "product_release_distinction": "MCBS years are releases. Cost supplement is a distinct product in the same program.",
        "rationale": "Beneficiary survey population file paired with the cost supplement.",
        "resolve": {"kind": "cms_title", "title": "Medicare Current Beneficiary Survey - Survey File"},
    },
    {
        "product_key": "cms-program-statistics-medicare-total-enrollment",
        "program_key": "cms-program-statistics",
        "title": "CMS Program Statistics - Medicare Total Enrollment",
        "domain": "population",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "CPS years are releases of this total-enrollment product.",
        "rationale": "Program-statistics enrollment totals, distinct from monthly enrollment extracts.",
        "resolve": {"kind": "cms_title", "title": "CMS Program Statistics - Medicare Total Enrollment"},
    },
    {
        "product_key": "census-acs-1year-selected-population-profiles",
        "program_key": "census-acs",
        "title": "ACS 1-Year Selected Population Profiles",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Selected-population-profile vintages are releases of this product.",
        "rationale": "Race/ethnicity/ancestry profiles are a distinct ACS table series.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSSPP1Y2024"},
    },
    {
        "product_key": "census-population-estimates-program",
        "program_key": "census-pep",
        "title": "Census Population Estimates Program",
        "domain": "population",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "PEP vintages are releases of this estimates product. Representative evidence is PEPPOP2021. Age/sex/race character files are related PEP products, not extra years of this total-population series.",
        "rationale": "Official population estimates used as denominators; vintages are not extra products.",
        "resolve": {"kind": "census_dataset", "dataset_id": "PEPPOP2021"},
    },
    # --- geography ---
    {
        "product_key": "census-acs-5year-comparison-profiles",
        "program_key": "census-acs",
        "title": "ACS 5-Year Comparison Profiles",
        "domain": "geography",
        "publisher": "U.S. Census Bureau",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Comparison-profile vintages are releases. This is not the Data Profiles product.",
        "rationale": "Named ACS geography task source for multi-year comparison tables.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSCP5Y2024"},
    },
    {
        "product_key": "cms-medicare-geographic-variation-national-state-county",
        "program_key": "cms-geographic-variation",
        "title": "Medicare Geographic Variation - by National, State & County",
        "domain": "geography",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual geographic-variation files are releases. HRR files are a distinct product.",
        "rationale": "County/state Medicare geography distinct from ACS geographies.",
        "resolve": {"kind": "cms_title", "title": "Medicare Geographic Variation - by National, State & County"},
    },
    {
        "product_key": "cms-medicare-geographic-variation-hrr",
        "program_key": "cms-geographic-variation",
        "title": "Medicare Geographic Variation - by Hospital Referral Region",
        "domain": "geography",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "HRR years are releases of this product, not a county-file year.",
        "rationale": "HRR geography is a different unit from county variation.",
        "resolve": {"kind": "cms_title", "title": "Medicare Geographic Variation - by Hospital Referral Region"},
    },
    {
        "product_key": "cdc-nonmedical-factor-measures-county-acs",
        "program_key": "cdc-nonmedical-factors-acs",
        "title": "Non-Medical Factor Measures for County, ACS 2017-2021",
        "domain": "geography",
        "publisher": "Centers for Disease Control and Prevention",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "ACS period and tract/ZCTA/place cuts are releases or geographic distributions of this SDOH-measures product. Representative evidence is the county table.",
        "rationale": "ACS-derived SDOH geography used in ACS geography tasks; tract files are not extra products.",
        "resolve": {"kind": "cdc_native", "source_id": "i6u4-y3g4"},
    },
    {
        "product_key": "cdc-atsdr-social-vulnerability-index",
        "program_key": "cdc-atsdr-svi",
        "title": "CDC/ATSDR Social Vulnerability Index",
        "domain": "geography",
        "publisher": "Agency for Toxic Substances and Disease Registry",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "SVI vintages and county/tract geographies are releases/distributions of this exact family. Catalog record ypqf-r5qs is HHS ASPE SVI and does not satisfy this family.",
        "rationale": "Named missing exact source family. Do not treat the ASPE catalog SVI as ATSDR SVI.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-043 C-043-1",
            "locator": "https://www.atsdr.cdc.gov/place-health/php/svi/index.html",
            "locator_kind": "publisher_product_page",
        },
    },
    {
        "product_key": "state-facility-licensure",
        "program_key": "state-facility-licensure",
        "title": "State facility licensure directories",
        "domain": "geography",
        "publisher": "State licensing agencies (jurisdiction-scoped)",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "Each state licensure directory is a distinct product. This freeze records the family for PR-044; one state is not national completeness.",
        "rationale": "Named missing family for facility identity outside Medicare enrollment.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-044 C-044-1",
            "locator": "https://www.cms.gov/medicare/health-safety-standards/certification-compliance",
            "locator_kind": "federal_certification_context_not_state_license",
        },
    },
    {
        "product_key": "census-acs-migration-flows",
        "program_key": "census-acs",
        "title": "ACS Migration Flows",
        "domain": "geography",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Flow vintages (including duplicate ACSFlows/ACSFLOWS portal records) are releases of this product. Representative evidence is ACSFLOWS2022.",
        "rationale": "County-to-county flows are a distinct ACS geography product.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSFLOWS2022"},
    },
    {
        "product_key": "cms-cjr-metropolitan-statistical-areas",
        "program_key": "cms-innovation-center",
        "title": "Comprehensive Care for Joint Replacement Model: Metropolitan Statistical Areas",
        "domain": "geography",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "CJR MSA lists by model year are releases.",
        "rationale": "Model-defined MSA geography, not ACS or HRR.",
        "resolve": {"kind": "cms_title", "title": "Comprehensive Care for Joint Replacement Model: Metropolitan Statistical Areas"},
    },
    {
        "product_key": "census-saipe-state-county",
        "program_key": "census-saipe",
        "title": "Small Area Income and Poverty Estimates: State and County",
        "domain": "geography",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "SAIPE is a time-series product; annual estimates are releases, not extra products. School-district SAIPE is a distinct product.",
        "rationale": "County poverty geography used with ACS/SVI tasks.",
        "resolve": {"kind": "census_dataset", "dataset_id": "SAIPESTATECOUNTY"},
    },
    {
        "product_key": "census-acs-5year-aian-detailed-tables",
        "program_key": "census-acs",
        "title": "ACS 5-Year American Indian and Alaska Native Detailed Tables",
        "domain": "geography",
        "publisher": "U.S. Census Bureau",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "AIAN detailed-table vintages are releases of this product, which is not the standard ACS detailed tables. Representative evidence is ACSDT5YAIAN2021.",
        "rationale": "AIAN geographic universe would be dropped by an easiest-100 rule.",
        "resolve": {"kind": "census_dataset", "dataset_id": "ACSDT5YAIAN2021"},
    },
    # --- public health ---
    {
        "product_key": "cdc-vsrr-provisional-maternal-death-counts",
        "program_key": "cdc-nvss-vsrr",
        "title": "VSRR Provisional Maternal Death Counts and Rates",
        "domain": "public health",
        "publisher": "National Center for Health Statistics",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Provisional VSRR periods are releases of this maternal-mortality product. Infant-mortality VSRR is a distinct product.",
        "rationale": "Named maternal-versus-infant mortality pair member.",
        "resolve": {"kind": "cdc_native", "source_id": "e2d5-ggg7"},
    },
    {
        "product_key": "cdc-vsrr-quarterly-infant-mortality",
        "program_key": "cdc-nvss-vsrr",
        "title": "NCHS - VSRR Quarterly provisional estimates for infant mortality",
        "domain": "public health",
        "publisher": "National Center for Health Statistics",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Quarterly provisional estimates are releases. This is not maternal VSRR and not the historical 1915-2013 infant-mortality series.",
        "rationale": "Named infant-mortality member of the maternal-versus-infant pair.",
        "resolve": {"kind": "cdc_native", "source_id": "jqwm-z2g9"},
    },
    {
        "product_key": "cdc-nchs-infant-mortality-rates-1915-2013",
        "program_key": "cdc-nchs-historical-vital-statistics",
        "title": "NCHS - Infant Mortality Rates, by Race: United States, 1915-2013",
        "domain": "public health",
        "publisher": "National Center for Health Statistics",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "This historical series is a completed product, not a year of provisional VSRR infant mortality.",
        "rationale": "Historical infant-mortality series retained so the pair is not reduced to one easy table.",
        "resolve": {"kind": "cdc_native", "source_id": "ddsk-zebd"},
    },
    {
        "product_key": "cdc-wonder-drug-overdose-death-rates",
        "program_key": "cdc-wonder",
        "title": "DQS Drug overdose death rates from CDC WONDER",
        "domain": "public health",
        "publisher": "National Center for Health Statistics",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "DQS portal rows are a catalog representation of WONDER-derived overdose rates, not a second WONDER product. WONDER query years are releases.",
        "rationale": "WONDER-derived overdose mortality; DQS is treated as portal evidence, not a duplicate product.",
        "resolve": {"kind": "cdc_native", "source_id": "rdjz-vn2n"},
    },
    {
        "product_key": "cdc-wonder-suicide-death-rates",
        "program_key": "cdc-wonder",
        "title": "DQS Death rates for suicide from CDC WONDER",
        "domain": "public health",
        "publisher": "National Center for Health Statistics",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Suicide rates are a distinct WONDER-derived product from overdose rates.",
        "rationale": "Second genuine WONDER-derived mortality product in the same program.",
        "resolve": {"kind": "cdc_native", "source_id": "w26f-tf3h"},
    },
    {
        "product_key": "cdc-nvss-low-birthweight",
        "program_key": "cdc-nvss",
        "title": "DQS NVSS Low birthweight live births, by state",
        "domain": "public health",
        "publisher": "National Center for Health Statistics",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "NVSS years are releases of this natality product, distinct from infant mortality.",
        "rationale": "Natality outcome used with infant-mortality tasks without conflating the two.",
        "resolve": {"kind": "cdc_native", "source_id": "ga7k-kycn"},
    },
    {
        "product_key": "cms-medicaid-opioid-prescribing-rates-geography",
        "program_key": "cms-opioid-prescribing",
        "title": "Medicaid Opioid Prescribing Rates - by Geography",
        "domain": "public health",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual geographic rates are releases. Part D opioid rates are a distinct product.",
        "rationale": "Medicaid opioid geography, not TAF microdata.",
        "resolve": {"kind": "cms_title", "title": "Medicaid Opioid Prescribing Rates - by Geography"},
    },
    {
        "product_key": "cms-medicare-part-d-opioid-prescribing-rates",
        "program_key": "cms-opioid-prescribing",
        "title": "Medicare Part D Opioid Prescribing Rates - by Geography",
        "domain": "public health",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual Part D opioid-rate files are releases of this product.",
        "rationale": "Medicare opioid geography is a distinct product from Medicaid opioid rates.",
        "resolve": {"kind": "cms_title", "title": "Medicare Part D Opioid Prescribing Rates - by Geography"},
    },
    {
        "product_key": "cms-medicare-diabetes-prevention-program",
        "program_key": "cms-innovation-center",
        "title": "Medicare Diabetes Prevention Program",
        "domain": "public health",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "MDPP participation/performance extracts are releases.",
        "rationale": "Prevention-program public health product inside CMS innovation reporting.",
        "resolve": {"kind": "cms_title", "title": "Medicare Diabetes Prevention Program"},
    },
    {
        "product_key": "hhs-aspe-social-vulnerability-index",
        "program_key": "hhs-aspe-svi",
        "title": "HHS ASPE Social Vulnerability Index",
        "domain": "public health",
        "publisher": "HHS Office of the Assistant Secretary for Planning and Evaluation",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "ASPE SVI vintages are releases of this catalog product. It is not CDC/ATSDR SVI.",
        "rationale": "Catalog SVI record is retained with an explicit non-ATSDR identity so the exact ATSDR family remains an intake.",
        "resolve": {"kind": "cdc_native", "source_id": "ypqf-r5qs"},
    },
    # --- prices ---
    {
        "product_key": "hospital-price-transparency-mrfs",
        "program_key": "cms-hospital-price-transparency",
        "title": "Hospital Price Transparency machine-readable files",
        "domain": "prices",
        "publisher": "Hospitals publishing under CMS Hospital Price Transparency rules",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "Per-hospital files and schema versions are releases/locators, not extra products. CMS enforcement tables are a different product and are not rate files.",
        "rationale": "Named MRF product layer. Selection of 25 hospitals is documented before any endpoint test.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-046 C-046-1",
            "locator": "https://github.com/CMSgov/hospital-price-transparency",
            "locator_kind": "publisher_schema_repository",
        },
    },
    {
        "product_key": "payer-transparency-in-coverage-mrfs",
        "program_key": "cms-transparency-in-coverage",
        "title": "Payer Transparency in Coverage machine-readable files",
        "domain": "prices",
        "publisher": "Payer reporting entities under CMS Transparency in Coverage rules",
        "named_priority": True,
        "access_expectation": "pending_source_intake",
        "product_release_distinction": "Index/in-network/allowed-amount/provider-reference files are file types of this product. HIOS issuer directory identity is not a TiC reporting-entity binding; PR-049 owns that binding.",
        "rationale": "Named payer MRF product. Ten issuer candidates stay fixed even if later unavailable.",
        "resolve": {
            "kind": "intake",
            "intake_task": "PR-049 C-049-1",
            "locator": "https://github.com/CMSgov/price-transparency-guide",
            "locator_kind": "publisher_schema_repository",
        },
    },
    {
        "product_key": "cms-hospital-price-transparency-enforcement",
        "program_key": "cms-hospital-price-transparency",
        "title": "Hospital Price Transparency Enforcement Activities and Outcomes",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": True,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Enforcement extracts are releases of this compliance product. They are not hospital rate files and cannot substitute for the MRF product.",
        "rationale": "Retained so enforcement data cannot be silently used as the MRF sample denominator.",
        "resolve": {"kind": "cms_title", "title": "Hospital Price Transparency Enforcement Activities and Outcomes"},
    },
    {
        "product_key": "cms-medicare-part-b-spending-by-drug",
        "program_key": "cms-drug-spending",
        "title": "Medicare Part B Spending by Drug",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual/quarterly drug-spend files are releases. Part D spending is a distinct product.",
        "rationale": "Part B drug spending, not a hospital chargemaster and not an MRF negotiated rate.",
        "resolve": {"kind": "cms_title", "title": "Medicare Part B Spending by Drug"},
    },
    {
        "product_key": "cms-medicare-part-d-spending-by-drug",
        "program_key": "cms-drug-spending",
        "title": "Medicare Part D Spending by Drug",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual Part D drug-spend files are releases of this product.",
        "rationale": "Part D spending-by-drug is a genuine second drug-spend product.",
        "resolve": {"kind": "cms_title", "title": "Medicare Part D Spending by Drug"},
    },
    {
        "product_key": "cms-clinical-lab-fee-schedule-private-payer-rates",
        "program_key": "cms-clinical-lab-fee-schedule",
        "title": "Medicare Clinical Laboratory Fee Schedule Private Payer Rates and Volumes",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "CLFS data-collection years are releases.",
        "rationale": "Private-payer lab rates used in price-definition tasks; not hospital MRFs.",
        "resolve": {"kind": "cms_title", "title": "Medicare Clinical Laboratory Fee Schedule Private Payer Rates and Volumes"},
    },
    {
        "product_key": "cms-medicaid-spending-by-drug",
        "program_key": "cms-drug-spending",
        "title": "Medicaid Spending by Drug",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual Medicaid drug-spend files are releases.",
        "rationale": "Medicaid drug spending is distinct from Medicare Part B/D spending products.",
        "resolve": {"kind": "cms_title", "title": "Medicaid Spending by Drug"},
    },
    {
        "product_key": "cms-quarterly-pdp-formulary-pharmacy-pricing",
        "program_key": "cms-part-d-formulary",
        "title": "Quarterly Prescription Drug Plan Formulary, Pharmacy Network, and Pricing Information",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Quarterly pricing drops are releases of this product, distinct from the monthly formulary/network file.",
        "rationale": "Plan-level pricing information, not TiC negotiated-rate MRFs.",
        "resolve": {"kind": "cms_title", "title": "Quarterly Prescription Drug Plan Formulary, Pharmacy Network, and Pricing Information"},
    },
    {
        "product_key": "cms-medicare-part-b-discarded-drug-units",
        "program_key": "cms-drug-spending",
        "title": "Medicare Part B Discarded Drug Units",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual discarded-unit files are releases of this product, not a year of Part B spending-by-drug.",
        "rationale": "Discarded-unit price/volume product used in price-definition edge cases.",
        "resolve": {"kind": "cms_title", "title": "Medicare Part B Discarded Drug Units"},
    },
    {
        "product_key": "cms-physician-supplier-procedure-summary",
        "program_key": "cms-medicare-provider-utilization-payment",
        "title": "Physician/Supplier Procedure Summary",
        "domain": "prices",
        "publisher": "Centers for Medicare & Medicaid Services",
        "named_priority": False,
        "access_expectation": "public_sample_eligible",
        "product_release_distinction": "Annual PSPS files are releases. Allowed charges in this file are not hospital MRF negotiated rates or patient expected bills.",
        "rationale": "Procedure-level Medicare allowed-charge summary for price-definition contrasts.",
        "resolve": {"kind": "cms_title", "title": "Physician/Supplier Procedure Summary"},
    },
]


def validate_catalog() -> None:
    keys = [item["product_key"] for item in PRODUCTS]
    if len(PRODUCTS) != 100:
        raise SystemExit(f"expected 100 products, found {len(PRODUCTS)}")
    if len(set(keys)) != 100:
        raise SystemExit("product_key is not unique")
    domains = {item["domain"] for item in PRODUCTS}
    if domains != set(DOMAINS):
        raise SystemExit(f"domain mismatch: {sorted(domains)}")
    counts = {domain: 0 for domain in DOMAINS}
    for item in PRODUCTS:
        counts[item["domain"]] += 1
    if any(count != 10 for count in counts.values()):
        raise SystemExit(f"domain counts must be 10 each: {counts}")
    program_keys = [item["program_key"] for item in PRODUCTS]
    if len(set(program_keys)) == 100:
        raise SystemExit("program_key unexpectedly unique; reuse is required")
