import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {parseWorkbookCells,parseTextCodebook} from './cms-structured-dictionary.mjs';
const cell=(reference,text,formula=null)=>({reference,text,formula});const doc=()=>({status:'captured_cells',sheets:[{name:'test',merged_cells:[],rows:[{row:1,cells:[cell('A1','POS Header'),cell('D1','Definition')]},{row:2,cells:[cell('A2','field'),cell('C2','Label'),cell('D2','Exact definition')]}]}]});
test('literal cell ownership and no approval',()=>{const p=parseWorkbookCells(doc());assert.equal(p.variables[0].description,'Exact definition');assert.equal(p.scientific_approval,false);});
test('duplicate or wrong-row cell fails closed',()=>{for(const c of [cell('A2','other'),cell('B3','bad')]){const d=doc();d.sheets[0].rows[1].cells.push(c);assert.throws(()=>parseWorkbookCells(d),/WORKBOOK_CELL_GEOMETRY/);}});
test('formula and merge rows not promoted',()=>{let d=doc();d.sheets[0].rows[1].cells[2].formula='1+1';assert.equal(parseWorkbookCells(d).variables.length,0);d=doc();d.sheets[0].merged_cells=['A2:B2'];assert.equal(parseWorkbookCells(d).variables.length,0);});
test('all duplicate identities isolated',()=>{const d=doc();d.sheets[0].rows.push({row:3,cells:[cell('A3','field'),cell('C3','Other'),cell('D3','Other definition')]});assert.equal(parseWorkbookCells(d).variables.length,0);});
test('blank TXT format preserves label, not definition',()=>{const p=parseTextCodebook('Variable           Format    Q#/Freq             Description/Label\nweight                                           Weight label');assert.equal(p.variables[0].publisher_format,null);assert.equal(p.variables[0].description,null);});
test('four captured complete dictionaries reproduce exact counts',async()=>{assert.ok(process.env.USHSO_RESEARCH_EVIDENCE_ROOT);const base=new URL('file://'+process.env.USHSO_RESEARCH_EVIDENCE_ROOT+'/review/cms-four-dictionaries/'),m=JSON.parse(await fs.readFile(new URL('manifest.json',base)));const counts=[];for(const e of m.results){const p=e.format==='txt'?parseTextCodebook(await fs.readFile(e.file,'utf8')):parseWorkbookCells(JSON.parse(await fs.readFile(e.file.replace('.xlsx','.cells-v2.json'))));counts.push([p.variables.length,p.variables.filter(v=>v.description).length]);}assert.deepEqual(counts,[[179,179],[342,0],[130,0],[4351,0]]);});
test('indented continuation retained without guessed ownership',()=>{const p=parseTextCodebook('Variable           Format    Q#/Freq             Description/Label\nfield              NUM                           Label\n                                                 continuation\n   Note: qualifier');assert.equal(p.unowned_context_lines.length,2);assert.equal(p.variables[0].publisher_context_lines,undefined);assert.equal(p.variables[0].description,null);assert.ok(p.unowned_context_lines.every(x=>x.ownership==='unknown'&&x.eligible_for_definition_assignment===false));});
