import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const exec=promisify(execFile),hash=b=>createHash('sha256').update(b).digest('hex'),scratch=[process.env.TMPDIR,process.env.RUNNER_TEMP].find(v=>typeof v==='string'&&path.isAbsolute(v)&&path.resolve(v)!=='/');assert.ok(scratch,'TMPDIR or RUNNER_TEMP scratch required');
async function fixture(fn){const root=await fs.mkdtemp(path.join(scratch,'window-resume-test-'));try{const out=path.join(root,'windows');await fs.mkdir(out);const pdf=path.join(root,'fixture.pdf'),pdfBytes=Buffer.from('%PDF-public-cache-test-only');await fs.writeFile(pdf,pdfBytes);const capture={status:'captured_window',pdf_sha256:hash(pdfBytes),start_page:1,count:1,total_pages:1,pypdf_version:'6.18.0',pages:[{physical_page:1,text:''}]},body=JSON.stringify(capture),receipt={pdf_sha256:hash(pdfBytes),extractor_sha256:hash(await fs.readFile(new URL('./pdf-text-window.py',import.meta.url))),windows:[{file:'1-1.json',sha256:hash(body),start_page:1,count:1}]};await fs.writeFile(path.join(out,'1-1.json'),body);await fs.writeFile(path.join(out,'resume.json'),JSON.stringify(receipt));const run=()=>exec(process.execPath,[fileURLToPath(new URL('./collect-pdf-windows.mjs',import.meta.url)),pdf,out],{timeout:25000,maxBuffer:1024*1024});await fn({out,pdf,capture,receipt,run});}finally{await fs.rm(root,{recursive:true,force:true});}}
test('tampered cached window rejected before reuse',()=>fixture(async({out,run})=>{await fs.appendFile(path.join(out,'1-1.json'),' ');await assert.rejects(run(),e=>e.stderr.includes('PDF_WINDOW_RESUME_HASH'));}));
test('changed extractor cannot inherit resume checkpoint',()=>fixture(async({out,receipt,run})=>{receipt.extractor_sha256='0'.repeat(64);await fs.writeFile(path.join(out,'resume.json'),JSON.stringify(receipt));await assert.rejects(run(),e=>e.stderr.includes('PDF_WINDOW_RESUME_EXTRACTOR'));}));
test('hash-consistent malformed page collection rejected',()=>fixture(async({out,capture,receipt,run})=>{capture.pages={};const body=JSON.stringify(capture);receipt.windows[0].sha256=hash(body);await fs.writeFile(path.join(out,'1-1.json'),body);await fs.writeFile(path.join(out,'resume.json'),JSON.stringify(receipt));await assert.rejects(run(),e=>e.stderr.includes('PDF_WINDOW_RESUME_IDENTITY'));}));
test('cached physical-page mismatch rejected',()=>fixture(async({out,capture,receipt,run})=>{capture.pages[0].physical_page=2;const body=JSON.stringify(capture);receipt.windows[0].sha256=hash(body);await fs.writeFile(path.join(out,'1-1.json'),body);await fs.writeFile(path.join(out,'resume.json'),JSON.stringify(receipt));await assert.rejects(run(),e=>e.stderr.includes('PDF_WINDOW_RESUME_IDENTITY'));}));
test('cached recheck atomically replaces checkpoint',()=>fixture(async({out,run})=>{await run();assert.equal(JSON.parse(await fs.readFile(path.join(out,'resume.json'))).completed,true);assert.ok(!(await fs.readdir(out)).some(x=>x.endsWith('.next.json')));}));
test('oversized source rejected before hashing',()=>fixture(async({pdf,run})=>{const h=await fs.open(pdf,'r+');await h.truncate(64*1024*1024+1);await h.close();await assert.rejects(run(),e=>e.stderr.includes('PDF_WINDOW_SOURCE_SIZE'));}));
