import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {makeConflictFixture} from './scientific-conflicts-fixture.mjs';
import {packageScientificConflicts,sha} from './package-scientific-conflicts.mjs';
import {routeScientificConflicts} from '../../worker/scientific-conflicts-router.mjs';
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ushso-conflict-fixture-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const f=await makeConflictFixture(root),files=new Map();async function walk(dir){for(const d of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,d.name);if(d.isDirectory())await walk(p);else files.set('/scientific-conflicts-v1/'+path.relative(f.output,p),await fs.readFile(p));}}await walk(f.output);const env={USHSO_SCIENTIFIC_CONFLICTS_REVIEW:'enabled',USHSO_SCIENTIFIC_CONFLICTS_MANIFEST_SHA256:sha(files.get('/scientific-conflicts-v1/manifest.json')),ASSETS:{fetch:async req=>new Response(files.get(new URL(req.url).pathname)??'',{status:files.has(new URL(req.url).pathname)?200:404})}};const call=async(id='record-0',extra={},use=env)=>{const r=await routeScientificConflicts(new Request('https://example.test/api/research/v1/scientific-conflicts?'+new URLSearchParams({record_id:id,generation:f.generation,...extra})),use,{loadCatalog:async()=>({corpus:{publication:{generation:f.generation}},records:f.records})});return {status:r.status,body:await r.json()};};return {...f,root,files,env,call};}
async function rewritePage(f,mutate){const manifestPath='/scientific-conflicts-v1/manifest.json',m=JSON.parse(f.files.get(manifestPath)),item=m.records[0],dp='/scientific-conflicts-v1/records/'+sha(item.record_id)+'.json',d=JSON.parse(f.files.get(dp)),page=d.pages[0],rows=JSON.parse(f.files.get('/scientific-conflicts-v1/pages/'+page.sha256+'.json'));mutate(rows,d);const b=Buffer.from(JSON.stringify(rows));page.sha256=sha(b);page.bytes=b.length;f.files.set('/scientific-conflicts-v1/pages/'+page.sha256+'.json',b);const db=Buffer.from(JSON.stringify(d));item.sha256=sha(db);f.files.set(dp,db);const mb=Buffer.from(JSON.stringify(m));f.files.set(manifestPath,mb);f.env.USHSO_SCIENTIFIC_CONFLICTS_MANIFEST_SHA256=sha(mb);}
test('portable seven-record fixture packages authoritative corpus count and all90 review rows',async(t)=>{const f=await fixture(t);assert.equal(f.records.length,7);let count=0;for(const r of f.records){let page=0;do{const x=await f.call(r.record_id,{page:String(page),...(page?{manifest_sha256:f.env.USHSO_SCIENTIFIC_CONFLICTS_MANIFEST_SHA256}:{})});assert.equal(x.status,200);count+=x.body.result.rows.length;page=x.body.result.next_page;}while(page!==null);}assert.equal(count,90);});
test('malformed rendered field types are typed503 even with a correctly repinned package',async(t)=>{for(const field of ['state','scope_warning','proposed_text','display_label']){const f=await fixture(t);await rewritePage(f,rows=>{rows[0][field]={unsafe:'object'}});const r=await f.call();assert.equal(r.status,503);assert.equal(r.body.error.code,'scientific_conflicts_binding');assert.equal((await f.call('record-6')).status,200);}});
test('duplicate preview IDs are rejected across descriptor page inventory',async(t)=>{const f=await fixture(t);await rewritePage(f,(rows,d)=>{rows[1].preview_id=rows[0].preview_id;d.pages[0].preview_ids[1]=d.pages[0].preview_ids[0];});assert.equal((await f.call()).status,503);});
test('disabled, stale continuation, missing pin and baseline changes fail closed',async(t)=>{const f=await fixture(t);assert.equal((await f.call('record-0',{},{})).status,404);assert.equal((await f.call('record-6',{page:'1'})).status,409);assert.equal((await f.call('record-0',{}, {...f.env,USHSO_SCIENTIFIC_CONFLICTS_MANIFEST_SHA256:null})).status,503);f.records[0].title='changed';assert.equal((await f.call()).status,503);});
test('generator refuses approval inheritance, stale packet, and local source path exposure',async(t)=>{for(const variant of ['approval','packet','path']){const f=await fixture(t),draft=JSON.parse(await fs.readFile(f.draftFile));if(variant==='approval')draft.owner_decision='approved';if(variant==='packet')draft.source_packet_sha256='f'.repeat(64);if(variant==='path')draft.cards[0].proposed_text='/home/private/source';await fs.writeFile(f.draftFile,JSON.stringify(draft));await assert.rejects(packageScientificConflicts({...f,output:path.join(f.root,'rejected')}));}});

test('declared page bytes must equal verified bytes even under a repinned descriptor',async(t)=>{const f=await fixture(t);await rewritePage(f,()=>{});const mp='/scientific-conflicts-v1/manifest.json',m=JSON.parse(f.files.get(mp)),item=m.records[0],dp='/scientific-conflicts-v1/records/'+sha(item.record_id)+'.json',d=JSON.parse(f.files.get(dp));d.pages[0].bytes--;const db=Buffer.from(JSON.stringify(d));f.files.set(dp,db);item.sha256=sha(db);const mb=Buffer.from(JSON.stringify(m));f.files.set(mp,mb);f.env.USHSO_SCIENTIFIC_CONFLICTS_MANIFEST_SHA256=sha(mb);assert.equal((await f.call()).status,503);assert.equal((await f.call('record-6')).status,200);});
